### ISSUE TITLE
Endpoint used by build.py blocked in mainland China

### ISSUE THREAD

**Issue by zyctinker** [LLK/scratch-blocks#1009]
### Expected Behavior

generate compressed files by py -2 build.py

### Actual Behavior
`$ py -2 build.py  
Warning: No description for CONTROLS_FOREVER  
Created file: .\msg/json/\en.json  
Created file: .\msg/json/\qqq.json  
SUCCESS: msg\js\en.js  
SUCCESS: blockly_uncompressed_horizontal.js  
SUCCESS: blockly_uncompressed_vertical.js  
Exception in thread Thread-3:  
Traceback (most recent call last):  
  File "C:\Python27\lib\threading.py", line 552, in __bootstrap_inner  
    self.run()  
  File "build.py", line 179, in run  
    self.gen_core(True)  
  File "build.py", line 215, in gen_core  
    self.do_compile(params, target_filename, filenames, "")  
  File "build.py", line 284, in do_compile  
    conn.request("POST", "/compile", urllib.urlencode(params), headers)  
  File "C:\Python27\lib\httplib.py", line 955, in request  
    self._send_request(method, url, body, headers)  
  File "C:\Python27\lib\httplib.py", line 989, in _send_request  
    self.endheaders(body)  
  File "C:\Python27\lib\httplib.py", line 951, in endheaders  
    self._send_output(message_body)  
  File "C:\Python27\lib\httplib.py", line 811, in _send_output  
    self.send(msg)  
  File "C:\Python27\lib\httplib.py", line 773, in send  
    self.connect()  
  File "C:\Python27\lib\httplib.py", line 754, in connect  
    self.timeout, self.source_address)  
  File "C:\Python27\lib\socket.py", line 553, in create_connection  
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):  
gaierror: [Errno 11004] getaddrinfo failed'  

### Operating System and Browser

Windows 7
python 2.7(together with python 3.5 so I use py -2 to launch python 2.7 )

**Comment by rachel-fenichel** [comment]
Have you had this problem repeatedly, or just the one time?

It looks like a problem with connecting to the server that runs compilation, so it might be transient.

For context, here are the docs on the closure compiler service: https://developers.google.com/closure/compiler/docs/api-tutorial1

**Comment by zyctinker** [comment]
I had this problem repeatedly. I have tried reinstall python 2.7 and scratch-block, but it didn't work

**Comment by xmeow** [comment]
@zyctinker , All you need is a VPN, the appspot got block in china mainland~

**Comment by joseeph** [comment]
indeed facing the same issue, couldn't get the compressed library build, even though vpn is on

**Comment by rachel-fenichel** [comment]
You can also use the offline closure compiler if you're frequently rebuilding.

**Comment by rachel-fenichel** [comment]
Instructions for using the offline compiler are now live: https://developers.google.com/blockly/guides/modify/web/advanced

**Comment by qiansitong** [comment]
@joseeph Have you solved the problem?I met the same issue

**Comment by cwillisf** [comment]
scratch-blocks v2 is a complete rewrite built on top of upstream [Blockly](https://github.com/RaspberryPiFoundation/blockly/). The old build system (Google Closure compiler, `python build.py`, the `core/` and `shim/` directories, etc.) no longer exists. This issue is no longer applicable. Thank you for reporting it!

If you believe this issue is still relevant to scratch-blocks v2, please let us know and we can reopen it.
