### ISSUE TITLE
Issues running `python build.py && webpack`

### ISSUE THREAD

**Issue by ZhangJoker** [LLK/scratch-blocks#1540]
I got an error like below,

```
Traceback (most recent call last):
  File "build.py", line 595, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-blocks@0.1.0 prepare: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

could you give me a help?

**Comment by thisandagain** [comment]
Please do not file duplicate issues. Tracking in https://github.com/LLK/scratch-gui/issues/2119
