### ISSUE TITLE
won't build

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-blocks#1730]
### Expected Behavior

I am trying to install as detailed here: https://github.com/LLK/scratch-blocks/wiki

I expect this to be successful

### Actual Behavior

`npm install` errors

```npm WARN deprecated travis-after-all@1.4.4: The functionality this package provided is now supported natively by Travis CI via Build Stages (see: https://blog.travis-ci.com/2017-05-11-introducing-build-stages).
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> fsevents@1.2.4 install /Users/George/Documents/Projects/ssm/website/scratch-blocks/node_modules/fsevents
> node install

[fsevents] Success: "/Users/George/Documents/Projects/ssm/website/scratch-blocks/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> scratch-blocks@0.1.0 prepublish /Users/George/Documents/Projects/ssm/website/scratch-blocks
> python build.py && webpack

Using local compiler: google-closure-compiler ...

SUCCESS: blockly_compressed_vertical.js
Size changed from 3083 KB to 939 KB (30%).
SUCCESS: blockly_uncompressed_horizontal.js
SUCCESS: blockly_uncompressed_vertical.js
SUCCESS: blockly_compressed_horizontal.js
Size changed from 3055 KB to 928 KB (30%).
SUCCESS: blocks_compressed_horizontal.js
Size changed from 39 KB to 19 KB (49%).
blocks_vertical/vertical_extensions.js:54: WARNING - Misplaced function annotation. This JSDoc is not attached to a function node. Are you missing parentheses?
  return function() {
  ^^^^^^^^^^^^^^^^^^^

0 error(s), 1 warning(s)
SUCCESS: blocks_compressed_vertical.js
Size changed from 173 KB to 87 KB (51%).
SUCCESS: blocks_compressed.js
Size changed from 21 KB to 8 KB (38%).
SUCCESS: javascript_compressed.js
Size changed from 18 KB to 12 KB (66%).
SUCCESS: python_compressed.js
Size changed from 12 KB to 6 KB (50%).
SUCCESS: php_compressed.js
Size changed from 11 KB to 5 KB (49%).
SUCCESS: dart_compressed.js
Size changed from 9 KB to 4 KB (46%).
SUCCESS: lua_compressed.js
Size changed from 7 KB to 3 KB (43%).
/Users/George/Documents/Projects/ssm/website/scratch-blocks/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/George/Documents/Projects/ssm/website/scratch-blocks/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/George/Documents/Projects/ssm/website/scratch-blocks/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/George/Documents/Projects/ssm/website/scratch-blocks/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/George/.npm/_logs/2018-10-06T13_01_07_872Z-debug.log
```

### Steps to Reproduce

1. `git clone https://github.com/LLK/scratch-blocks.git`
2. `cd scratch-blocks`
3. `ln -s $(npm root)/google-closure-library ../closure-library`
4. `npm install`

### Operating System and Browser

macOS 10.14  
node v9.8.0  
npm 5.6.0  
Python 2.7.15

**Comment by sunyton** [comment]
same to mine ...

**Comment by xuhow** [comment]
solved: https://github.com/webpack/webpack/issues/8082

**Comment by thisandagain** [comment]
This *should* be resolved in the latest `webpack`. Can you give it another try and let us know if you continue to have problems?
