### ISSUE TITLE
build.py cannot find file

### ISSUE THREAD

**Issue by danbulant** [LLK/scratch-blocks#1859]
I downloaded the zip file and extracted it in my www directory. I did `npm install` and it ended with following error:

> WindowsError: error[2] Windows cannot find file
Here is log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepublish' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prepublish' ]
5 info lifecycle scratch-blocks@0.1.0~prepublish: scratch-blocks@0.1.0
6 verbose lifecycle scratch-blocks@0.1.0~prepublish: unsafe-perm in lifecycle true
7 verbose lifecycle scratch-blocks@0.1.0~prepublish: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\WinNMP\WWW\scratchware\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Daniel\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Daniel\AppData\Local\Programs\Python\Python36\;C:\Ruby25-x64\bin;C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps;C:\WinNMP\bin;C:\Users\Daniel\AppData\Local\Programs\Python\Python37;C:\Users\Daniel\AppData\Roaming\npm;C:\Users\Daniel\AppData\Local\Programs\Python\Python37\Scripts;C:\Python27\;
8 verbose lifecycle scratch-blocks@0.1.0~prepublish: CWD: C:\WinNMP\WWW\scratchware
9 silly lifecycle scratch-blocks@0.1.0~prepublish: Args: [ '/d /s /c', 'python build.py && webpack' ]
10 silly lifecycle scratch-blocks@0.1.0~prepublish: Returned: code: 1  signal: null
11 info lifecycle scratch-blocks@0.1.0~prepublish: Failed to exec prepublish script
12 verbose stack Error: scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid scratch-blocks@0.1.0
14 verbose cwd C:\WinNMP\WWW\scratchware
15 verbose Windows_NT 10.0.17763
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepublish"
17 verbose node v10.15.0
18 verbose npm  v6.4.1
19 error code ELIFECYCLE
20 error errno 1
21 error scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
21 error Exit status 1
22 error Failed at the scratch-blocks@0.1.0 prepublish script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```
My OS and PC:
Amd 64bit
Windows 10 (non-activated, but I think it's not the problem)
NPM 6.4.1
Python 2.7.14

**Comment by apple502j** [comment]
Use Linux machine or Cygwin.

**Comment by danbulant** [comment]
I have kali installed (sub-system) as I heard that it can help, but it didn't. I can't use linux because of some problems with drivers for AMD radeon GPUs...

**Comment by Mfweb** [comment]
This problem still exists.
```shell
$ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> scratch-blocks@0.1.0 prepublish C:\Users\h\Desktop\scratch-blocks-develop
> python build.py && webpack

Traceback (most recent call last):
  File "build.py", line 574, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "D:\Python2\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "D:\Python2\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\h\AppData\Roaming\npm-cache\_logs\2019-04-03T09_35_17_555Z-debug.log

```

**Comment by d3x0r** [comment]
same problem... temporary fix...

(before 'fix' )

```
M:\javascript\scratch-blocks>python build.py
*SUCCESS: google-closure-compilerbuild\test_input.js* this line isn't normally there, 
*so there's no idea what the error really is or what 'file' it failed to find... surely a 
*catch could be done that could show the command line that failed - why 
*doesn't the python runtime just do that anyway?
Traceback (most recent call last):
  File "build.py", line 575, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "c:\tools\python27\LIB\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\tools\python27\LIB\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

changing line 54 of build.py 

``` diff
--- CLOSURE_COMPILER_NPM = "google-closure-compiler"
+++ CLOSURE_COMPILER_NPM = "google-closure-compiler.cmd"


which I would have liked to do ... but no ? operator
+++ CLOSURE_COMPILER_NPM = process.platform=="win32"?"google-closure-compiler.cmd":"google-closure-compiler"
```

Then this is the output - made progress... 
(Why can't Python Just run .cmd files?)

```
M:\javascript\scratch-blocks>python build.py
SUCCESS: google-closure-compiler.cmdbuild\test_input.js
Using local compiler: google-closure-compiler ...

Exception in thread Thread-4:
Traceback (most recent call last):
  File "c:\tools\python27\LIB\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build.py", line 227, in run
    self.gen_core(True)
  File "build.py", line 263, in gen_core
    self.do_compile(params, target_filename, filenames, "")
  File "build.py", line 305, in do_compile
    json_data = do_compile(params, target_filename)
  File "build.py", line 331, in do_compile_local
    proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "c:\tools\python27\LIB\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\tools\python27\LIB\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

SUCCESS: blockly_uncompressed_vertical.jsSUCCESS: blockly_uncompressed_horizontal.js
```

and 

```
# build.py like line 328
---       for group in [["google-closure-compiler"], dash_args]:
+++      for group in [[CLOSURE_COMPILER_NPM], dash_args]:
```

but then 

```
SUCCESS2: google-closure-compiler.cmd--compilation_levelSIMPLE--language_inECMASCRIPT_2017--language_outECMASCRIPT5--rewrite_polyfillsfalse--definegoog.DEBUG=falsecore\block.jscore\block_animations.jscore\block_drag_surface.jscore\block_dragger.jscore\block_events.jscore\block_render_svg_vertical.jscore\block_svg.jscore\blockly.jscore\blocks.jscore\bubble.jscore\bubble_dragger.jscore\colours.jscore\comment.jscore\comment_events.jscore\connection.jscore\connection_db.jscore\constants.jscore\contextmenu.jscore\css.jscore\data_category.jscore\dropdowndiv.jscore\events.jscore\events_abstract.jscore\extensions.jscore\field.jscore\field_angle.jscore\field_checkbox.jscore\field_colour.jscore\field_colour_slider.jscore\field_dropdown.jscore\field_iconmenu.jscore\field_image.jscore\field_label.jscore\field_label_serializable.jscore\field_matrix.jscore\field_note.jscore\field_number.jscore\field_numberdropdown.jscore\field_textdropdown.jscore\field_textinput.jscore\field_textinput_removable.jscore\field_variable.jscore\field_variable_getter.jscore\field_vertical_separator.jscore\flyout_base.jscore\flyout_button.jscore\flyout_dragger.jscore\flyout_extension_category_header.jscore\flyout_horizontal.jscore\flyout_vertical.jscore\generator.jscore\gesture.jscore\grid.jscore\icon.jscore\inject.jscore\input.jscore\insertion_marker_manager.jscore\msg.jscore\mutator.jscore\names.jscore\options.jscore\procedures.jscore\rendered_connection.jscore\scratch_block_comment.jscore\scratch_blocks_utils.jscore\scratch_bubble.jscore\scratch_events.jscore\scratch_msgs.jscore\scrollbar.jscore\toolbox.jscore\tooltip.jscore\touch.jscore\trashcan.jscore\ui_events.jscore\ui_menu_utils.jscore\utils.jscore\variable_events.jscore\variable_map.jscore\variable_model.jscore\variables.jscore\warning.jscore\widgetdiv.jscore\workspace.jscore\workspace_audio.jscore\workspace_comment.jscore\workspace_comment_render_svg.jscore\workspace_comment_svg.jscore\workspace_drag_surface_svg.jscore\workspace_dragger.jscore\workspace_svg.jscore\xml.jscore\zoom_controls.jsnode_modules\google-closure-library\closure\goog\a11y\aria\aria.jsnode_modules\google-closure-library\closure\goog\a11y\aria\attributes.jsnode_modules\google-closure-library\closure\goog\a11y\aria\datatables.jsnode_modules\google-closure-library\closure\goog\a11y\aria\roles.jsnode_modules\google-closure-library\closure\goog\array\array.jsnode_modules\google-closure-library\closure\goog\asserts\asserts.jsnode_modules\google-closure-library\closure\goog\async\animationdelay.jsnode_modules\google-closure-library\closure\goog\async\delay.jsnode_modules\google-closure-library\closure\goog\async\freelist.jsnode_modules\google-closure-library\closure\goog\async\nexttick.jsnode_modules\google-closure-library\closure\goog\async\run.jsnode_modules\google-closure-library\closure\goog\async\workqueue.jsnode_modules\google-closure-library\closure\goog\base.jsnode_modules\google-closure-library\closure\goog\color\color.jsnode_modules\google-closure-library\closure\goog\color\names.jsnode_modules\google-closure-library\closure\goog\debug\debug.jsnode_modules\google-closure-library\closure\goog\debug\entrypointregistry.jsnode_modules\google-closure-library\closure\goog\debug\error.jsnode_modules\google-closure-library\closure\goog\debug\errorcontext.jsnode_modules\google-closure-library\closure\goog\debug\logbuffer.jsnode_modules\google-closure-library\closure\goog\debug\logger.jsnode_modules\google-closure-library\closure\goog\debug\logrecord.jsnode_modules\google-closure-library\closure\goog\disposable\disposable.jsnode_modules\google-closure-library\closure\goog\disposable\idisposable.jsnode_modules\google-closure-library\closure\goog\dom\animationframe\polyfill.jsnode_modules\google-closure-library\closure\goog\dom\asserts.jsnode_modules\google-closure-library\closure\goog\dom\browserfeature.jsnode_modules\google-closure-library\closure\goog\dom\classlist.jsnode_modules\google-closure-library\closure\goog\dom\dom.jsnode_modules\google-closure-library\closure\goog\dom\htmlelement.jsnode_modules\google-closure-library\closure\goog\dom\nodeiterator.jsnode_modules\google-closure-library\closure\goog\dom\nodetype.jsnode_modules\google-closure-library\closure\goog\dom\safe.jsnode_modules\google-closure-library\closure\goog\dom\tagiterator.jsnode_modules\google-closure-library\closure\goog\dom\tagname.jsnode_modules\google-closure-library\closure\goog\dom\tags.jsnode_modules\google-closure-library\closure\goog\dom\vendor.jsnode_modules\google-closure-library\closure\goog\events\browserevent.jsnode_modules\google-closure-library\closure\goog\events\browserfeature.jsnode_modules\google-closure-library\closure\goog\events\event.jsnode_modules\google-closure-library\closure\goog\events\eventhandler.jsnode_modules\google-closure-library\closure\goog\events\eventid.jsnode_modules\google-closure-library\closure\goog\events\events.jsnode_modules\google-closure-library\closure\goog\events\eventtarget.jsnode_modules\google-closure-library\closure\goog\events\eventtype.jsnode_modules\google-closure-library\closure\goog\events\focushandler.jsnode_modules\google-closure-library\closure\goog\events\keycodes.jsnode_modules\google-closure-library\closure\goog\events\keyhandler.jsnode_modules\google-closure-library\closure\goog\events\listenable.jsnode_modules\google-closure-library\closure\goog\events\listener.jsnode_modules\google-closure-library\closure\goog\events\listenermap.jsnode_modules\google-closure-library\closure\goog\events\mousewheelhandler.jsnode_modules\google-closure-library\closure\goog\fs\url.jsnode_modules\google-closure-library\closure\goog\functions\functions.jsnode_modules\google-closure-library\closure\goog\fx\anim\anim.jsnode_modules\google-closure-library\closure\goog\fx\animation.jsnode_modules\google-closure-library\closure\goog\fx\animationqueue.jsnode_modules\google-closure-library\closure\goog\fx\dom.jsnode_modules\google-closure-library\closure\goog\fx\dragger.jsnode_modules\google-closure-library\closure\goog\fx\transition.jsnode_modules\google-closure-library\closure\goog\fx\transitionbase.jsnode_modules\google-closure-library\closure\goog\html\safehtml.jsnode_modules\google-closure-library\closure\goog\html\safescript.jsnode_modules\google-closure-library\closure\goog\html\safestyle.jsnode_modules\google-closure-library\closure\goog\html\safestylesheet.jsnode_modules\google-closure-library\closure\goog\html\safeurl.jsnode_modules\google-closure-library\closure\goog\html\trustedresourceurl.jsnode_modules\google-closure-library\closure\goog\html\uncheckedconversions.jsnode_modules\google-closure-library\closure\goog\i18n\bidi.jsnode_modules\google-closure-library\closure\goog\iter\iter.jsnode_modules\google-closure-library\closure\goog\labs\useragent\browser.jsnode_modules\google-closure-library\closure\goog\labs\useragent\engine.jsnode_modules\google-closure-library\closure\goog\labs\useragent\platform.jsnode_modules\google-closure-library\closure\goog\labs\useragent\util.jsnode_modules\google-closure-library\closure\goog\log\log.jsnode_modules\google-closure-library\closure\goog\math\box.jsnode_modules\google-closure-library\closure\goog\math\coordinate.jsnode_modules\google-closure-library\closure\goog\math\irect.jsnode_modules\google-closure-library\closure\goog\math\math.jsnode_modules\google-closure-library\closure\goog\math\rect.jsnode_modules\google-closure-library\closure\goog\math\size.jsnode_modules\google-closure-library\closure\goog\object\object.jsnode_modules\google-closure-library\closure\goog\promise\promise.jsnode_modules\google-closure-library\closure\goog\promise\resolver.jsnode_modules\google-closure-library\closure\goog\promise\thenable.jsnode_modules\google-closure-library\closure\goog\reflect\reflect.jsnode_modules\google-closure-library\closure\goog\string\const.jsnode_modules\google-closure-library\closure\goog\string\string.jsnode_modules\google-closure-library\closure\goog\string\stringbuffer.jsnode_modules\google-closure-library\closure\goog\string\typedstring.jsnode_modules\google-closure-library\closure\goog\structs\structs.jsnode_modules\google-closure-library\closure\goog\structs\trie.jsnode_modules\google-closure-library\closure\goog\style\bidi.jsnode_modules\google-closure-library\closure\goog\style\style.jsnode_modules\google-closure-library\closure\goog\timer\timer.jsnode_modules\google-closure-library\closure\goog\ui\colorpalette.jsnode_modules\google-closure-library\closure\goog\ui\colorpicker.jsnode_modules\google-closure-library\closure\goog\ui\component.jsnode_modules\google-closure-library\closure\goog\ui\container.jsnode_modules\google-closure-library\closure\goog\ui\containerrenderer.jsnode_modules\google-closure-library\closure\goog\ui\control.jsnode_modules\google-closure-library\closure\goog\ui\controlcontent.jsnode_modules\google-closure-library\closure\goog\ui\controlrenderer.jsnode_modules\google-closure-library\closure\goog\ui\idgenerator.jsnode_modules\google-closure-library\closure\goog\ui\menu.jsnode_modules\google-closure-library\closure\goog\ui\menuheader.jsnode_modules\google-closure-library\closure\goog\ui\menuheaderrenderer.jsnode_modules\google-closure-library\closure\goog\ui\menuitem.jsnode_modules\google-closure-library\closure\goog\ui\menuitemrenderer.jsnode_modules\google-closure-library\closure\goog\ui\menurenderer.jsnode_modules\google-closure-library\closure\goog\ui\menuseparator.jsnode_modules\google-closure-library\closure\goog\ui\menuseparatorrenderer.jsnode_modules\google-closure-library\closure\goog\ui\palette.jsnode_modules\google-closure-library\closure\goog\ui\paletterenderer.jsnode_modules\google-closure-library\closure\goog\ui\rangemodel.jsnode_modules\google-closure-library\closure\goog\ui\registry.jsnode_modules\google-closure-library\closure\goog\ui\selectionmodel.jsnode_modules\google-closure-library\closure\goog\ui\separator.jsnode_modules\google-closure-library\closure\goog\ui\slider.jsnode_modules\google-closure-library\closure\goog\ui\sliderbase.jsnode_modules\google-closure-library\closure\goog\ui\tree\basenode.jsnode_modules\google-closure-library\closure\goog\ui\tree\treecontrol.jsnode_modules\google-closure-library\closure\goog\ui\tree\treenode.jsnode_modules\google-closure-library\closure\goog\ui\tree\typeahead.jsnode_modules\google-closure-library\closure\goog\useragent\platform.jsnode_modules\google-closure-library\closure\goog\useragent\product.jsnode_modules\google-closure-library\closure\goog\useragent\product_isversion.jsnode_modules\google-closure-library\closure\goog\useragent\useragent.js
The command line is too long.
UNKNOWN ERROR
```
so the build fails anyway.

**Comment by LAST-iMP** [comment]
add "shell=True" to the end of subprocess.Popen
proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, shell=True);

**Comment by upupming** [comment]
Confirmed not working on Windows Python 2.7.16

**Comment by chua1989** [comment]
I hava same problem in Windows  Python 2.7.16

Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

$ python build.py
closure_compiler: google-closure-compiler
os.path.join: build\test_input.js
Traceback (most recent call last):
  File "build.py", line 577, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by cwillisf** [comment]
scratch-blocks v2 is a complete rewrite built on top of upstream [Blockly](https://github.com/RaspberryPiFoundation/blockly/). The old build system (Google Closure compiler, `python build.py`, the `core/` and `shim/` directories, etc.) no longer exists. This issue is no longer applicable. Thank you for reporting it!

If you believe this issue is still relevant to scratch-blocks v2, please let us know and we can reopen it.
