### ISSUE TITLE
thread.py error

### ISSUE THREAD

**Issue by liugyer** [LLK/scratch-blocks#2073]
### Expected Behavior
npm install ------ successful.

### Actual Behavior

Using remote compiler: closure-compiler.appspot.com ...

Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Software\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build.py", line 229, in run
    self.gen_core(True)
  File "build.py", line 266, in gen_core
    self.do_compile(params, target_filename, filenames, "")
  File "build.py", line 332, in do_compile
    json_data = do_compile(params, target_filename)
  File "build.py", line 405, in do_compile_remote
    conn.request("POST", "/compile", urllib.urlencode(remoteParams), headers)
  File "D:\Software\Python27\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "D:\Software\Python27\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "D:\Software\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "D:\Software\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "D:\Software\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "D:\Software\Python27\lib\httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "D:\Software\Python27\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "D:\Software\Python27\lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10060]
### Steps to Reproduce
1、using vpn
2、npm install
I have tried so many times, this is still failed.

### Operating System and Browser
Windows 10

**Comment by apple502j** [comment]
@liugyer This is probably because of the VPN software or firewalls.
