### ISSUE TITLE
build issue on window system

### ISSUE THREAD

**Issue by vd-6** [LLK/scratch-blocks#2076]
Traceback (most recent call last):
  File "build.py", line 574, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by apple502j** [comment]
This should be fixed once #2020 is merged

**Comment by vd-6** [comment]
i have made some changes in build.py now its working for me please this changes is it fine 

line 331 :  proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
modify :  proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, shell=True)
line 574 :  test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
modify:  test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, shell=True)

**Comment by vd-6** [comment]
hi
i have update build.py manually now its working for me could you please let me know how can i merge this file using git

**Comment by cwillisf** [comment]
scratch-blocks v2 is a complete rewrite built on top of upstream [Blockly](https://github.com/RaspberryPiFoundation/blockly/). The old build system (Google Closure compiler, `python build.py`, the `core/` and `shim/` directories, etc.) no longer exists. This issue is no longer applicable. Thank you for reporting it!

If you believe this issue is still relevant to scratch-blocks v2, please let us know and we can reopen it.
