### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by usaidsherwani** [LLK/scratch-blocks#3052]
having these errors while doing npm install

`
scratch-blocks@0.1.0 prepublish
 python build.py && webpack

Using local compiler: google-closure-compiler.cmd ...

The command line is too long.
UNKNOWN ERROR
SUCCESS: blockly_uncompressed_horizontal.js
 SUCCESS: blockly_uncompressed_vertical.js
The command line is too long.
UNKNOWN ERROR
SUCCESS: blocks_compressed_horizontal.js
Size changed from 39 KB to 19 KB (49%).
SUCCESS: blocks_compressed_vertical.js
Size changed from 179 KB to 90 KB (50%).
SUCCESS: blocks_compressed.js
Size changed from 22 KB to 8 KB (37%).
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (F:\B\scratch-blocks-develop\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (F:\B\scratch-blocks-develop\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (F:\B\scratch-blocks-develop\node_modules\webpack\lib\NormalModule.js:471:10)
    at F:\B\scratch-blocks-develop\node_modules\webpack\lib\NormalModule.js:503:5
    at F:\B\scratch-blocks-develop\node_modules\webpack\lib\NormalModule.js:358:12
    at F:\B\scratch-blocks-develop\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (F:\B\scratch-blocks-develop\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (F:\B\scratch-blocks-develop\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (F:\B\scratch-blocks-develop\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at F:\B\scratch-blocks-develop\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at F:\B\scratch-blocks-develop\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
npm ERR! code 1
npm ERR! path F:\B\scratch-blocks-develop
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c python build.py && webpack
`

**Comment by CST1229** [comment]
Applying #2138's changes to build.py makes it work for me, try doing that.

**Comment by alexcui03** [comment]
set environment variable `NODE_OPTIONS` to `--openssl-legacy-provider`

**Comment by zhaohao0305** [comment]
have you resolved it

**Comment by cwillisf** [comment]
scratch-blocks v2 is a complete rewrite built on top of upstream [Blockly](https://github.com/RaspberryPiFoundation/blockly/). The old build system (Google Closure compiler, `python build.py`, the `core/` and `shim/` directories, etc.) no longer exists. This issue is no longer applicable. Thank you for reporting it!
